### PR TITLE
Support keep annotation sections for entity's fields

### PR DESCRIPTION
**Pull request by rockerhieu**
Implement keep annotation sections for entity's fields as described in http://gonzalo.huerta.cl/?p=142

Example:
```java
// KEEP INCLUDES - put your custom includes here
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
@JsonIgnoreProperties(ignoreUnknown = true)
// KEEP INCLUDES END
/**
 * Entity mapped to table USER_ENTITY.
 */
public class UserEntity {

    // KEEP _id ANNOTATIONS - put your custom annotations here
    @JsonIgnore
    // KEEP ANNOTATIONS END
    private Long _id;
    // KEEP id ANNOTATIONS - put your custom annotations here
    // KEEP ANNOTATIONS END
    private String id;
    // KEEP fullname ANNOTATIONS - put your custom annotations here
    @JsonProperty("full_name")
    // KEEP ANNOTATIONS END
    private String fullname;
    // KEEP gender ANNOTATIONS - put your custom annotations here
    // KEEP ANNOTATIONS END
    private int gender;

    //....

}
```

### CODE REVIEW

**Comment by rockerhieu** [comment]
Anyone?

**Comment by rockerhieu** [comment]
Personally I'm fine with the boilerplate as it is easier to customize. We won't edit the generated code often so it's not a big deal. How about having a setting to toggle them? i.e `Schema#enableKeepFieldsAnnotationsByDefault()`

**Comment by matir91** [comment]
is It possible to add annotations to a relationship entity?
I've two classes, A and B. A has many B.
I need to add an annotation to B field in the A class, is this possible?
Particularly I need add a Parceler annotation (https://github.com/johncarl81/parceler)

**Comment by matir91** [comment]
Is it possible to add annotations to a relationship entity?
I've two classes, A and B. A has many B.
I need to add an annotation to B field in the A class, is this possible?
Particularly I need add a Parceler annotation (https://github.com/johncarl81/parceler)

**Comment by danimontoya** [comment]
@matir91 did u get that working? Is it possible to add the annotation as u wanted to do it?

**Pull request closed without merging**
